/**
 * Course: CSE 341
 * Semester and Year: Spring 2021
 * Assignment: Database Systems
 * Author: Derei, Tal
 * User ID: tad222
 */

import java.util.Scanner;
import java.sql.Connection;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import java.sql.SQLException;
import java.io.*;

/**
 * Insurance database for executing SQL queries using JBDC
 */
public class insurance {
    /**
     * Establish a connection to the Oracle database
     */
    public Boolean connect_database(String user, String pass) {
        
        try (Connection connection = DriverManager.getConnection("jdbc:oracle:thin:@edgar1.cse.lehigh.edu:1521:cse241",user,pass);
            Statement statement = connection.createStatement();
        ) {
            System.out.println("Connection to the oracle database succeeded!\n");
        } catch (SQLException exception) {
            // exception.printStackTrace();
            System.out.println("connection to the oracle database failed! Try again!");
            return false;
        }
        return true;
    }

    /**
     * CLI for customer interface
     */
    public void customer(int interfaces) {
        System.out.println("[1] Create a new customer in the database\n");
        System.out.println("[2] Add a policy\n");
        System.out.println("[3] Drop a policy\n");
        System.out.println("[4] Make a claim\n");
        System.out.println("[5] Add/remove/replace a vehicle\n");
    }

    /**
     * CLI for agent interface
     */
    public void agent(int interfaces) {
        System.out.println("[1] Identify customers with overdue bills\n");
        System.out.println("[2] Customers with pending claims that have not been serviced recently\n");
        System.out.println("[3] Compute revenue generated by the agent\n");
    }

    /**
     * CLI for adjuster interface
     */
    public void adjuster(int interfaces) {
        System.out.println("[1] Identify claims that have not been serviced recently\n");
        System.out.println("[2] Remediation firms or body shops to claims\n");
    }

    /**
     * CLI for corperate interface
     */
    public void corperate(int interfaces) {
        System.out.println("[1] Generate report on revenue\n");
        System.out.println("[2] Generate report on claims paid\n");
        System.out.println("[3] Generate report on profits based on policy type\n");
        System.out.println("[4] Generate report on profitability of a customer\n");
    }
}